healthcheck_port: 6969
packet_limit: 8192 # 8 * 1024
protocol: "tcp"
healthcheck_message: 'te estas portando mal'
healthcheck_response: 'seras castigada'
max_retries: 5
retry_delay: 1s
interval: 5s
max_connection_retries: 15
connection_retry_delay: 2s
ttl: 5

services:
  - 'server'
  - 'accumulator-main'
  - 'accumulator-montreal'
  - 'accumulator-stations'
  - 'calculator1'
  - 'calculator2'
  - 'calculator3'
  - 'distributor1'
  - 'distributor2'
  - 'distributor3'
  - 'joiner-montreal'
  - 'joiner-stations'
  - 'joiner-weather'
  - 'worker-station1'
  - 'worker-station2'
  - 'worker-station3'
  - 'worker-trip1'
  - 'worker-trip2'
  - 'worker-trip3'
  - 'worker-weather1'
  - 'worker-weather2'
  - 'worker-weather3'