healthcheck_port: 6969
packet_limit: 8192 # 8 * 1024
protocol: "tcp"
healthcheck_message: 'te estas portando mal'
healthcheck_response: 'seras castigada'
max_retries: 5
retry_delay: 1s
interval: 5s
max_connection_retries: 10
connection_retry_delay: 1s
ttl: 5

services:
  - 'server'
#  - 'accumulatorMain'
#  - 'accumulatorMontreal'
#  - 'accumulatorStationAvg'
#  - 'calculator1'
#  - 'calculator2'
#  - 'calculator3'
#  - 'distributor1'
#  - 'distributor2'
#  - 'distributor3'
#  - 'joinerMontreal'
#  - 'joinerStation'
#  - 'joinerWeather'
#  - 'worker-station1'
#  - 'worker-station2'
#  - 'worker-station3'
#  - 'worker-trip1'
#  - 'worker-trip2'
#  - 'worker-trip3'
#  - 'worker-weather1'
#  - 'worker-weather2'
#  - 'worker-weather3'